import {
    GridBox, TextEdit, ListView, VerticalBox
} from "std-widgets.slint";

import {
    HexView
} from "hexview.slint";

export component MainView inherits Window {
    title: "Gbhiera";
    preferred-width: 800px;
    preferred-height: 600px;

    in-out property <string> status: "Gbhiera";

    GridBox {
        Row {
            HexView {
            }
            VerticalBox {
                padding: 0px;
                ListView {
                }
                TextEdit {
                    text: "Element info!";
                }
            }
        }

        Text {
            colspan: 2;
            text: root.status;
            wrap: word_wrap;
            overflow: elide;
        }
    }
}
