import {
    Button, TextEdit, LineEdit, ListView, GridBox
} from "std-widgets.slint";

import {
    HexView
} from "hexview.slint";

import {
    ElementExplorer
} from "element.slint";

export component GbhieraUI inherits Window {
    title: "Gbhiera";
    icon: @image-url("./gbhiera.png");
    preferred-width: 800px;
    preferred-height: 600px;

    in-out property <string> status: "Gbhiera";
    in-out property <string> binary-path <=> le_binary.text;
    in-out property <int> total-line-count <=> hexview.total-line-count;
    in-out property <int> line-count <=> hexview.line-count;

    callback reload-file(string);
    callback show-open-dialog();
    pure callback get-line <=> hexview.get-line;

    GridBox {
        Row {
            HorizontalLayout {
                colspan: 2;
                Text { text: "File:"; vertical-alignment: center; horizontal-alignment: right; }
                le_binary := LineEdit {
                    accepted => { root.reload-file(le_binary.text); }
                    horizontal_stretch: 1;
                }
                open_button := Button {
                    text: "📂";
                    clicked => { root.show-open-dialog(); }
                }
            }
        }

        Row {
            hexview := HexView {
                font-family: "Courier New";
                font-size: 12pt;
                horizontal_stretch: 0.8;
            }
            VerticalLayout {
                ElementExplorer {
                }
                TextEdit {
                    text: "Element info!";
                }
                horizontal_stretch: 0.2;
            }
        }

        Text {
            colspan: 2;
            text: root.status;
            wrap: word_wrap;
            overflow: elide;
        }
    }
}
