import { HorizontalBox, TextEdit, ListView, VerticalBox, ScrollView, Slider, GridBox} from "std-widgets.slint";
export component HexView inherits ScrollView {
    pure callback render_plot(int /* view_start */, int /* view_height */) -> image;

    hex-view := Image {
        x: 0;
        y: - root.viewport-y;
        source: root.render_plot(self.y / 1px, root.visible-height / 1px);
        // image-fit: contain;
        touch := TouchArea {
            property <float> pressed-pitch;
            property <float> pressed-yaw;
            pointer-event(event) => {
                if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                    // self.pressed-pitch = root.pitch;
                    // self.pressed-yaw = root.yaw;
                }
            }
            moved => {
                if (self.enabled && self.pressed) {
                    // root.pitch = self.pressed-pitch + (touch.mouse-y - touch.pressed-y) / self.height * 3.14;
                    // root.yaw = self.pressed-yaw - (touch.mouse-x - touch.pressed-x) / self.width * 3.14;
                }
            }
            // mouse-cursor: self.pressed ? MouseCursor.grabbing : MouseCursor.grab;
        }
    }
}
